name: UKit
main: cat.nyaa.ukit.SpigotLoader
version: ${project.version}
softdepend:
  - Vault
  - ECore
  - EssentialsChat
  - LuckPerms
api-version: 1.18
authors:
  - Nyaacat Community
commands:
  ukit:
    description: "ukit commands. Use /ukit help for more information."
    usage: /ukit <args...>
    aliases:
      - u